name: Backend – Build & Deploy

on:
  push:
    branches:
      - main
    paths:
      - "digipin_server/**"
      - "digipin_agent/**"
      - ".github/workflows/backend-deploy.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        working-directory: digipin_server
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Static analysis (syntax check)
        run: |
          python -m compileall digipin_agent digipin_server

      - name: Trigger Render backend deploy
        if: success() && env.RENDER_DEPLOY_HOOK != ''
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}
        run: |
          curl -fsS -X POST "$RENDER_DEPLOY_HOOK"

